### ekf config file ###
ekf_filter_node:
  ros__parameters:
    frequency: 16.0
    two_d_mode: true
    publish_tf: true
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    ## x,     y,      z
    ## roll,  pitch,  yaw,
    ## vx,    vy,     vz,
    ## vroll, vpitch, vyaw,
    ## ax,    ay,     az

    odom0: /diffdrive_controller/odom
    odom0_config: [true, true, false,  
                   false, false, false,
                   true, false, true,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 2
    
    imu0: /imu
    imu0_config: [false, false, false,
                  true, true, true,
                  true, true, true,
                  false, false, false,
                  true, true, true]
    imu0_queue_size: 2



    # Which velocities are being controlled. Order is vx, vy, vz, vroll, vpitch, vyaw.
    control_config: [true, false, false, false, false, true]